all: base
base:
	g++ -std=c++11 -I/usr/local/include/eigen3 \
		-o ./compiled/debug_sinimin_fwer ./main/debug_sinimin_fwer.cpp

# 	g++ -std=c++11 -I/usr/local/include/eigen3 \
# 		-o ./compiled/debug_siniminWY ./main/debug_siniminWY.cpp

# 		g++-6 -std=c++11 -I/usr/local/include/eigen3 \
# 		-o ./compiled/siniminFWER_test ./main/sinimin_fwer_test.cpp

# 	g++ -std=c++11 -Wall -Wextra -pedantic  \
# 		-o ./compiled/interval_test ./main/interval_test.cpp

# 	g++ -std=c++11 -Wall -Wextra -pedantic  \
# 		-o ./compiled/support_test ./main/support_test.cpp

# 	g++-6 -std=c++11 -I/usr/local/include/eigen3 \
# 		-o ./compiled/edge_epistasis ./main/edge_epistasis.cpp

# 	g++-6 -std=c++11 -I/usr/local/include/eigen3 \
# 		-o ./compiled/edge_epistasis_wy ./main/edge_epistasis_wy.cpp 

# 	g++-6 -std=c++11 -I/usr/local/include/eigen3 \
# 		-o ./compiled/check_data_classes ./main/check_data_classes.cpp 

# 	g++-6 -std=c++11 -I/usr/local/include/eigen3 \
# 	-o ./compiled/check_tarone_classes ./main/check_tarone_classes.cpp 

# 	g++-6 -std=c++11 -I/usr/local/include/eigen3 \
# 			-o ./compiled/check_binary_data_classes \
# 			./main/check_binary_data_classes.cpp 

# 	g++-6 -std=c++11 -I/usr/local/include/eigen3 \
# 	-o ./compiled/check_tarone_wy_classes ./main/check_tarone_wy_classes.cpp 