all: base
base:
# 	g++-6 -std=c++11 -I/usr/local/include/eigen3 \
# 		-o ./compiled/check_data_classes ./main/check_data_classes.cpp 

# 		g++-6 -std=c++11 -I/usr/local/include/eigen3 \
# 		-o ./compiled/check_tarone_classes ./main/check_tarone_classes.cpp 

# 		g++-6 -std=c++11 -I/usr/local/include/eigen3 \
# 				-o ./compiled/check_binary_data_classes \
# 				./main/check_binary_data_classes.cpp 

		g++-6 -std=c++11 -I/usr/local/include/eigen3 \
		-o ./compiled/check_tarone_wy_classes ./main/check_tarone_wy_classes.cpp 


